# Use una imagen base oficial de Node.js
FROM node:14

# Establezca el directorio de trabajo en /app
WORKDIR /app

# Copie package.json y package-lock.json
COPY package*.json ./

# Instale las dependencias del proyecto
RUN npm install

# Copie el resto de los archivos del proyecto
COPY . .

# Exponga el puerto en el que la aplicación se ejecutará
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["node", "app.js"]
